src/elements/TEI.xml, src/elements/back.xml, src/elements/body.xml, src/elements/div.xml, src/elements/docImprint.xml, src/elements/pubPlace.xml, src/elements/publisher.xml, src/elements/signed.xml, src/examples/back.xml, src/examples/body.xml, src/examples/div.xml, src/examples/docImprint.xml, src/examples/examples.xml
=> Examples module textstructure

src/elements/editorialDecl.xml, test/elements/test_editorialDecl.py
=> [feat]: added constraint for tei:editorialDecl

src/elements/add.xml, src/elements/addSpan.xml, src/elements/damage.xml, src/elements/damageSpan.xml, src/elements/del.xml, src/elements/delSpan.xml, src/elements/fw.xml, src/elements/gap.xml, src/elements/handShift.xml, src/elements/space.xml, src/elements/subst.xml, src/elements/supplied.xml, src/elements/unclear.xml, src/examples/back.xml, src/examples/damage.xml, src/examples/examples.xml, src/examples/fw.xml, src/examples/handShift.xml, src/examples/space.xml, src/examples/subst.xml, src/examples/supplied.xml
=> Examples module transcr

src/elements/cell.xml, test/elements/test_cell.py
This will allow us to optionally specifiy the alignment of text inside a table cell.
=> [feat]: allow @rend for tei:cell

src/schema/commons/content.odd.xml, src/schema/elements/date.xml, src/schema/elements/origDate.xml, src/schema/elements/origPlace.xml, src/schema/elements/origin.xml, src/schema/elements/pb.xml
=> Origdate and origplace

src/schema/commons/classes.odd.xml, src/schema/commons/datatypes.odd.xml, src/schema/elements/handNote.xml, src/schema/examples/examples.xml, src/schema/examples/handDesc.xml, tests/src/schema/elements/test_ab.py, tests/src/schema/elements/test_add.py, tests/src/schema/elements/test_damage.py, tests/src/schema/elements/test_del.py, tests/src/schema/elements/test_handNote.py, tests/src/schema/elements/test_handShift.py
We're using a closed list values instead...
=> [fix]: removed IDREF as datatype from @hand

src/schema/commons/classes.odd.xml, src/schema/commons/constraints.odd.xml, src/schema/commons/content.odd.xml, src/schema/elements/ab.xml, src/schema/elements/add.xml, src/schema/elements/body.xml, src/schema/elements/del.xml, src/schema/elements/div.xml, src/schema/elements/gap.xml, src/schema/elements/orgName.xml, src/schema/elements/p.xml, src/schema/elements/persName.xml, src/schema/elements/seg.xml, tests/src/schema/elements/test_ab.py, tests/src/schema/elements/test_body.py, tests/src/schema/elements/test_div.py
- [fix]: decouple att.canonical and att.naming
- [fix]: datatype for tei:gap/@source
- [refac]: content model tei:body, tei:div, tei:p, tei:seg
See commit details.
=> Misc fixes

docs/base/transcription.de.md, src/docs/base/date.de.md
=> Datierungsrichtlinien

src/schema/elements/div.xml, src/schema/examples/body.xml
=> fix-module-textstructure

src/schema/commons/classes.odd.xml, src/schema/elements/addSpan.xml, src/schema/elements/damageSpan.xml, src/schema/elements/delSpan.xml
=> [refac]: exchanged ß with ss for compliance with swiss german

src/schema/commons/datatypes.odd.xml, src/schema/elements/gap.xml, src/schema/elements/space.xml
The Elements tei:space and tei:gap both use the attributes @unit and @quantity.
Changed possible values for these attributes.
=> fix-module-transcr

src/schema/elements/abbr.xml, src/schema/elements/addSpan.xml, src/schema/elements/anchor.xml, src/schema/elements/app.xml, src/schema/elements/author.xml, src/schema/elements/back.xml, src/schema/elements/date.xml, src/schema/elements/editor.xml, src/schema/elements/fw.xml, src/schema/elements/gap.xml, src/schema/elements/hi.xml, src/schema/elements/idno.xml, src/schema/elements/lb.xml, src/schema/elements/num.xml, src/schema/elements/orgName.xml, src/schema/elements/q.xml, src/schema/elements/quote.xml, src/schema/elements/rdg.xml, src/schema/elements/resp.xml, src/schema/elements/sourceDesc.xml, src/schema/examples/abbr.xml, src/schema/examples/app.xml, src/schema/examples/examples.xml, src/schema/examples/foreign.xml, src/schema/examples/hi.xml, src/schema/examples/respStmt.xml, src/schema/examples/supplied.xml
=> Correction core

src/schema/elements/handDesc.xml, src/schema/elements/origDate.xml, src/schema/elements/origPlace.xml, src/schema/elements/seal.xml, src/schema/elements/supportDesc.xml, src/schema/elements/witness.xml, src/schema/examples/examples.xml, src/schema/examples/foliation.xml, src/schema/examples/history.xml, src/schema/examples/msIdentifier.xml, src/schema/examples/origDate.xml, src/schema/examples/sealDesc.xml, src/schema/examples/summary.xml, tests/src/schema/elements/test_history.py, tests/src/schema/elements/test_origDate.py, tests/src/schema/elements/test_origPlace.py, tests/src/schema/elements/test_origin.py
=> Corr modul ms descritpion

src/docs/base/abbreviation-list.de.md, src/docs/base/dating_guidelines.de.md, src/docs/base/hyphenation.de.md, src/schema/elements/date.xml
=> Fix dating guidelines

src/docs/base/hyphenation.de.md, src/docs/base/transcription/index.de.md, src/docs/base/transcription/semantic-markup/index.de.md, src/docs/base/transcription/semantic-markup/keyword_entries.de.md, src/docs/base/transcription/semantic-markup/lemmata.de.md, src/docs/base/transcription/semantic-markup/organisations.de.md, src/docs/base/transcription/semantic-markup/persons.de.md, src/docs/base/transcription/semantic-markup/places.de.md, src/docs/base/transcription/spelling/index.de.md, src/docs/base/transcription/spelling/numbers.de.md, src/docs/base/transcription/spelling/punctuation.de.md, src/docs/base/transcription/spelling/special.de.md, src/docs/base/transcription/spelling/wordseparation.de.md, src/docs/elements/index.de.md
=> Correct transcriptions guidelines

src/docs/base/dating_guidelines.de.md, src/schema/examples/examples.xml
=> Corrigenda datierungsrichtlinien

src/schema/commons/constraints.odd.xml, src/schema/commons/datatypes.odd.xml, src/schema/elements/idno.xml, src/schema/elements/keywords.xml, src/schema/elements/measure.xml, src/schema/elements/measureGrp.xml, src/schema/elements/msContents.xml, src/schema/elements/orgName.xml, src/schema/elements/origDate.xml, src/schema/elements/respStmt.xml, src/schema/elements/summary.xml, src/schema/elements/text.xml, src/schema/examples/respStmt.xml, tests/src/schema/elements/test_TEI.py, tests/src/schema/elements/test_fileDesc.py, tests/src/schema/elements/test_history.py, tests/src/schema/elements/test_idno.py, tests/src/schema/elements/test_listWit.py, tests/src/schema/elements/test_measure.py, tests/src/schema/elements/test_measureGrp.py, tests/src/schema/elements/test_msContents.py, tests/src/schema/elements/test_orgName.py, tests/src/schema/elements/test_origDate.py, tests/src/schema/elements/test_origin.py, tests/src/schema/elements/test_respStmt.py, tests/src/schema/elements/test_sourceDesc.py, tests/src/schema/elements/test_summary.py, tests/src/schema/elements/test_teiHeader.py, tests/src/schema/elements/test_witness.py, tests/src/schema/examples/msDesc.xml
=> Minor corrections to schema

src/schema/commons/classes.odd.xml, src/schema/elements/pb.xml, src/schema/examples/examples.xml, src/schema/examples/pb.xml
=> Correct example for tei:pb

src/schema/elements/div.xml
This PR removes `@type="collection"` from the `<div/>`-element. This value can be considered as obsolete, because we are now typing the 
`<text>`-element.
=> [fix]: removed type collection from tei:div

src/schema/commons/datatypes.odd.xml
=> Korr @place

src/schema/commons/classes.odd.xml, src/schema/elements/quote.xml, tests/src/schema/elements/test_quote.py
=> Minor fixes

src/schema/elements/author.xml, src/schema/elements/item.xml, src/schema/elements/label.xml, src/schema/elements/lb.xml, src/schema/elements/list.xml, src/schema/elements/measure.xml, src/schema/elements/measureGrp.xml, src/schema/elements/orig.xml, src/schema/elements/placeName.xml, src/schema/elements/q.xml, src/schema/elements/quote.xml, src/schema/elements/ref.xml, src/schema/elements/textLang.xml, src/schema/elements/title.xml, src/schema/elements/unclear.xml, src/schema/examples/author.xml, src/schema/examples/examples.xml, src/schema/examples/label.xml, src/schema/examples/lb.xml, src/schema/examples/list.xml, src/schema/examples/measure.xml, src/schema/examples/measureGrp.xml, src/schema/examples/orig.xml, src/schema/examples/placeName.xml, src/schema/examples/q.xml, src/schema/examples/quote.xml, src/schema/examples/ref.xml, src/schema/examples/title.xml, src/schema/examples/unclear.xml
=> examples module core

src/schema/elements/pb.xml, src/schema/elements/summary.xml, src/schema/examples/examples.xml, src/schema/examples/pb.xml, src/schema/examples/summary.xml
=> New examples

src/schema/commons/constraints.odd.xml, src/schema/elements/additional.xml, src/schema/elements/adminInfo.xml, src/schema/elements/custEvent.xml, src/schema/elements/custodialHist.xml, src/schema/elements/msDesc.xml, src/schema/examples/adminInfo.xml, src/schema/examples/examples.xml, src/schema/main.odd.xml, tests/src/schema/elements/test_adminInfo.py, tests/src/schema/elements/test_custEvent.py, tests/src/schema/elements/test_custodialHist.py, tests/src/schema/elements/test_msDesc.py, tests/src/schema/elements/test_quote.py
- [test/fix]: attribute value test for tei:quote
- [feat]: added element adminInfo with children
=> Extend schema with element adminInfo

src/schema/commons/datatypes.odd.xml, tests/src/schema/elements/test_damage.py
This commit adds new attribute values and renames some old values.
=> feat: Modified @agent

src/schema/commons/datatypes.odd.xml, src/schema/elements/origDate.xml, src/schema/elements/origPlace.xml, src/schema/elements/origin.xml, src/schema/main.odd.xml, tests/src/schema/elements/test_history.py, tests/src/schema/elements/test_origPlace.py, tests/src/schema/elements/test_origin.py
=> feat: changed tei:origin, tei:origDate, tei:origPlace

src/schema/commons/patterns.odd.xml, tests/src/schema/elements/test_pb.py
This allows zeros at the end like in '_20'
=> [feat]: extend name pattern for facs-attribute

src/schema/elements/damage.xml, tests/src/schema/elements/test_damage.py
This commit allows the attributes @unit and @dimensions for tei:damage and restrict possible attribute values like for tei:space.
=> feat: added attributes to tei:damage

src/schema/elements/measure.xml
=> fix: allow 'klafter' for length and area

src/schema/elements/app.xml, src/schema/examples/app.xml, src/schema/examples/examples.xml, tests/src/schema/elements/test_app.py
This commit makes tei:lem optional, because there are cases where no word of the edited text is suitable als lemma in an apparatus entry.
=> feat: made tei:lem optional in tei:app

src/schema/commons/patterns.odd.xml, tests/src/schema/elements/test_rdg.py
- fix: update ssrq.witness.pointer
- [fix]: pattern for urn:ssrq
=> Fix various patterns based on RegEx

src/schema/elements/measureGrp.xml, src/schema/elements/origin.xml, src/schema/examples/history.xml, tests/src/schema/elements/test_measureGrp.py, tests/src/schema/elements/test_origin.py
=> Minor schema changes

src/schema/commons/patterns.odd.xml, src/schema/elements/note.xml, tests/src/schema/elements/test_gap.py, tests/src/schema/elements/test_note.py
=> Minor changes

src/schema/elements/head.xml, tests/src/schema/elements/test_head.py
This commit allows tei:p inside tei:head
=> feat: changed content model for tei:head

src/schema/commons/classes.odd.xml, tests/src/schema/elements/test_corr.py, tests/src/schema/elements/test_supplied.py
This PR:
- allows multiple entries in @resp
- forbids lower case letters in @resp, all abbreviations must be upper case.
=> Modify resp

src/schema/commons/datatypes.odd.xml
=> Origin update

src/schema/commons/datatypes.odd.xml, src/schema/elements/add.xml, src/schema/elements/addSpan.xml, tests/src/schema/elements/test_addSpan.py
=> [feat]: allow attribute type for tei:addSpan

src/schema/elements/subst.xml, tests/src/schema/elements/test_subst.py
=> Allow pb in subst

src/schema/main.odd.xml
=> [fix]: reference new datatype in main.odd.xml

src/schema/elements/lem.xml, tests/src/schema/elements/test_lem.py
This commit allows tei:seg in tei:lem to structure large tei:lem-entries.
=> feat: allow tei:seg in tei:lem

src/schema/elements/head.xml, tests/src/schema/elements/test_head.py
This commit allows the usage of tei:seg inside tei:head to structure large headings.
=> feat: allowed tei:seg in tei:head

src/schema/commons/datatypes.odd.xml, src/schema/elements/seg.xml
=> Allow pb in seg

src/schema/elements/seg.xml, tests/src/schema/elements/test_seg.py
This commit allows the usage of tables inside segments in combination with paragraphs.
=> feat: allow tei:table in tei:seg

src/schema/commons/datatypes.odd.xml
=> Kleinschreibung von engrogne

src/schema/elements/supplied.xml, tests/src/schema/elements/test_supplied.py
This commit allows to have tei:p in tei:supplied
=> feat: allow-p-in-supplied

src/schema/elements/ab.xml, tests/src/schema/elements/test_ab.py
This commit allows the attribute @rend for tei:ab
=> feat: allow @rend for tei:ab

.github/actions/mike/action.yml
We've missed the breaking-changes: [https://github.com/jimporter/mike/releases/tag/v2.0.0](https://github.com/jimporter/mike/releases/tag/v2.0.0)
=> [ci]: fix arguments for deploying with mike

src/docs/base/transcription/spelling/numbers.de.md, src/schema/elements/num.xml, src/schema/examples/num.xml, tests/src/schema/elements/test_num.py
=> feat: changed rules for fractional numbers

src/schema/elements/hi.xml, src/schema/examples/examples.xml, src/schema/examples/hi.xml
rotated_90
rotated_180
rotated_270
are now possible attribute values for hi @rend
=> feat: new attribute values for rend

.pre-commit-config.yaml, utils/commons/filehandler.py, utils/docs/specs/oddelement.py, utils/schema/steps/step.py
=> refac: reformatted files

src/schema/commons/classes.odd.xml, src/schema/commons/datatypes.odd.xml, src/schema/elements/date.xml, src/schema/elements/measure.xml, src/schema/examples/date.xml, src/schema/examples/examples.xml, src/schema/examples/measure.xml
This PR refactors all example in the classses.odd.xml and datatypes.odd.xml.
Most of the examples were duplictates with examples for specific elements
and could be removed.
=> Commons examples

src/schema/elements/quote.xml, tests/src/schema/elements/test_quote.py
=> Corr quote

src/schema/commons/constraints.odd.xml, src/schema/commons/content.odd.xml, src/schema/elements/pc.xml, src/schema/main.odd.xml, tests/src/schema/elements/test_pc.py, tests/src/schema/test_constraints.py
- **feat: constraint which ensure no nbsp is used**
- **feat: added element tei:pc**
=> Add tei:pc and don't allow nbsp any longer

src/schema/commons/content.odd.xml, src/schema/elements/note.xml, tests/src/schema/elements/test_note.py, tests/src/schema/elements/test_p.py
- **feat: removed type original from tei:note**
- **feat: restrict usage of tei:corr**
Fixes the issues described in the following tickets:
- https://histhub.ssrq-sds-fds.ch/redmine/issues/3860
- https://histhub.ssrq-sds-fds.ch/redmine/issues/3861
=> remove note-type and restrict tei:corr

src/schema/elements/ab.xml
=> feat: allow additional place values for tei:ab

src/schema/commons/classes.odd.xml, src/schema/commons/constraints.odd.xml, src/schema/commons/content.odd.xml, src/schema/elements/extent.xml, tests/src/schema/elements/test_extent.py
Feat: Forbids tei:measure inside tei:extent 
Refac: Moves constraints to constraint.odd.xml
Refac: Moves tei:pc from content default to content display
=> Misc changes and refacs

src/schema/commons/classes.odd.xml, tests/src/schema/elements/test_measure.py
=> feat: allowed unkown for tei:measure/@quantity

src/schema/elements/seg.xml, src/schema/examples/examples.xml
=> feat: made documentation on numbering more clear

src/schema/commons/classes.odd.xml, src/schema/commons/datatypes.odd.xml, src/schema/elements/ab.xml, src/schema/elements/author.xml, src/schema/elements/cell.xml, src/schema/elements/custEvent.xml, src/schema/elements/date.xml, src/schema/elements/dimensions.xml, src/schema/elements/figure.xml, src/schema/elements/fw.xml, src/schema/elements/gap.xml, src/schema/elements/graphic.xml, src/schema/elements/hi.xml, src/schema/elements/idno.xml, src/schema/elements/label.xml, src/schema/elements/list.xml, src/schema/elements/material.xml, src/schema/elements/note.xml, src/schema/elements/pb.xml, src/schema/elements/seal.xml, src/schema/elements/supplied.xml, src/schema/elements/term.xml, src/schema/elements/text.xml
=> Attribute translations

src/schema/examples/app.xml
=> fix: corrected example

src/schema/commons/datatypes.odd.xml
=> new origin

src/schema/examples/damage.xml
Exchanged deprecated attribute values with new ones.
=> fix: fixed examples

src/schema/elements/material.xml, src/schema/elements/pb.xml
=> fix: corrected translation mistake

src/schema/commons/classes.odd.xml, src/schema/commons/datatypes.odd.xml, src/schema/elements/TEI.xml, src/schema/elements/repository.xml, src/schema/elements/settlement.xml, src/schema/main.odd.xml
also made @xml:lang required for tei:TEI.
=> refac/feat: changes to language definitions

src/schema/commons/constraints.odd.xml, tests/src/schema/elements/test_date.py, tests/src/schema/test_constraints.py
=> feat: added constraint for tei:date to not be empty outside tei:header

src/schema/elements/title.xml, tests/src/schema/elements/test_title.py
=> feat: allow tei:pc in tei:title

src/schema/commons/datatypes.odd.xml
=> fix: translation of tei:add @type="sign"

src/schema/elements/signed.xml, src/schema/examples/examples.xml
=> Löschen von unsinniger Bemerkung

src/docs/base/dating_guidelines.de.md, src/schema/elements/div.xml, src/schema/elements/item.xml, src/schema/elements/list.xml, src/schema/elements/quote.xml, src/schema/examples/date.xml, src/schema/examples/examples.xml, src/schema/examples/list.xml, src/schema/examples/quote.xml, tests/src/schema/elements/test_div.py, tests/src/schema/elements/test_list.py, utils/docs/extensions/md_xi.py, utils/schema/compile.py
=> feat: a lot of small changes

src/schema/elements/div.xml, tests/src/schema/elements/test_div.py
=> feat: allowed attribute xml:lang for tei:div

src/docs/base/transcription/spelling/punctuation.de.md, src/docs/base/transcription/spelling/versalia.de.md, src/docs/base/transcription/spelling/wordseparation.de.md
=> Ergänzung Drucke

src/schema/elements/measure.xml
=> feat: added documentation

src/schema/commons/patterns.odd.xml, tests/src/schema/elements/test_pb.py
=> feat: allowed "r" and "v" for pb/@n

src/schema/elements/ref.xml, tests/src/schema/elements/test_ref.py
tei:ref should be enclosed by tei:bibl if it contains a reference to another SLS-document.
=> feat: added constraint for tei:ref

src/schema/commons/datatypes.odd.xml, src/schema/elements/damage.xml, src/schema/elements/gap.xml, src/schema/elements/space.xml
=> refac: merged datatypes typography and base.line

src/schema/elements/ref.xml, tests/src/schema/elements/test_note.py, tests/src/schema/elements/test_ref.py
exception 1: editorialDecl/p/ref
exception 2: app/note[@type="text_comparison"]/ref
=> feat: ref is now required to be enclosed in bibl

src/schema/elements/pubPlace.xml, src/schema/elements/publisher.xml, tests/src/schema/elements/test_docImprint.py, tests/src/schema/elements/test_pubPlace.py, tests/src/schema/elements/test_publisher.py
=> Doc imprint and pub place

src/schema/elements/sic.xml, tests/src/schema/elements/test_sic.py
=> feat: allowed abbr in sic

src/schema/commons/classes.odd.xml, src/schema/elements/gap.xml, src/schema/elements/idno.xml, src/schema/elements/quote.xml, src/schema/elements/supplied.xml
Every element that uses @source now has its own content model and description for this attribute.
=> feat: modified @source

src/schema/commons/datatypes.odd.xml
=> doc: description of @type for tei:origPlace

src/docs/index.de.md, src/schema/commons/datatypes.odd.xml
=> Corr measure

src/schema/commons/classes.odd.xml, src/schema/commons/constraints.odd.xml, src/schema/commons/datatypes.odd.xml, src/schema/commons/modules.odd.xml, src/schema/commons/patterns.odd.xml, src/schema/commons/translations.odd.xml, src/schema/elements/bibl.xml, src/schema/elements/handNote.xml, src/schema/elements/idno.xml, src/schema/elements/orgName.xml, src/schema/elements/origDate.xml, src/schema/elements/origPlace.xml, src/schema/elements/persName.xml, src/schema/elements/placeName.xml, src/schema/elements/pubPlace.xml, src/schema/elements/seg.xml, src/schema/elements/settlement.xml, src/schema/elements/supplied.xml, src/schema/elements/term.xml, src/schema/elements/time.xml, src/schema/elements/witness.xml, src/schema/examples/examples.xml
=> refactor docs (commons)

src/schema/commons/constraints.odd.xml, src/schema/elements/date.xml, tests/src/schema/elements/test_date.py
=> fix: new schematron rules for tei:date

src/schema/commons/constraints.odd.xml, src/schema/elements/idno.xml, tests/src/schema/commons/test_constraints.py
- **fix: calendar constraint to exclude tei:time**
- **fix: role for idno constraint**
Prepares 1.3.2 Hotfix.
=> fix time calendar and constraint

src/schema/elements/head.xml, tests/src/schema/elements/test_head.py
This commits forbids some attributes for tei:head, if tei:head is inside tei:msDesc
=> feat: attributes in @head

src/schema/commons/datatypes.odd.xml
Corrected erroneous translation
=> changed value for tei:resp

src/schema/commons/classes.odd.xml, src/schema/commons/datatypes.odd.xml, src/schema/elements/measure.xml, tests/src/schema/elements/test_measure.py
- **fix: allow "Stuck" as volume**
- **fix: allow "Vierling" as weight**
=> 1.4.2 various fixes

src/docs/base/abbreviation-list.fr.md, src/docs/base/dating_guidelines.fr.md, src/docs/base/hyphenation.fr.md, src/docs/base/transcription/semantic-markup/organisations.fr.md, src/docs/base/transcription/semantic-markup/persons.fr.md, src/docs/base/transcription/spelling/normalization.fr.md, src/docs/base/transcription/spelling/numbers.fr.md, src/docs/base/transcription/spelling/punctuation.fr.md, src/docs/base/transcription/spelling/special.fr.md, src/docs/base/transcription/spelling/versalia.fr.md, src/docs/base/transcription/spelling/wordseparation.fr.md, src/docs/base/transcription/text-constitution/abbreviations.fr.md, src/docs/base/transcription/text-constitution/textstructure.fr.md
- before :;!? where they are punctuation signs
- after « and before »
=> feat: added empty spaces

utils/docs/specs/attributespec.py
=> Fix hi rend sup in desc

src/schema/elements/body.lit.xml, src/schema/elements/div.lit.xml, src/schema/elements/listBibl.lit.xml, tests/src/schema/conftest.py, tests/src/schema/elements/test_body_lit.py, tests/src/schema/elements/test_div_lit.py, tests/src/schema/elements/test_graphic_intro.py, tests/src/schema/elements/test_listBibl_lit.py, tests/src/schema/elements/test_orgName_intro.py, tests/src/schema/elements/test_orgName_lit.py, tests/src/schema/elements/test_publisher_intro.py, tests/src/schema/elements/test_publisher_lit.py
=> Simplify div list bibl in lit schema

src/schema/commons/datatypes.odd.xml, src/schema/elements/ab.xml, src/schema/elements/hi.intro.xml, src/schema/elements/hi.xml, src/schema/elements/p.xml, src/schema/intro.odd.xml, tests/src/schema/commons/test_constraints.py, tests/src/schema/elements/test_ab.py, tests/src/schema/elements/test_p.py
- **feat: restrict usage of tei:ab inside tei:p**
- **feat: warn the user, if tei:hi is the only child of tei:ab**
- **fix: constraint syntax for tei:p**
- **feat: extend allowed values of rend-attribute in tei:ab**
=> enhance restrict ab

src/schema/elements/measure.xml, tests/src/schema/elements/test_measure.py
=> feat: Stuck is now a weight unit

src/schema/elements/back.xml, src/schema/elements/quote.xml, tests/src/schema/elements/test_back.py, tests/src/schema/elements/test_quote.py
tei:note inside tei:back has to be removed. This may be a conversion issue.
=> feat: constraint to forbid tei:note in tei:back

src/schema/elements/hi.xml, tests/src/schema/elements/test_hi.py
=> Multiple attribute values for hi

src/schema/elements/author.xml, tests/src/schema/elements/test_author.py
=> feat: remove tei:orgName from tei:author

src/schema/commons/patterns.odd.xml, tests/src/schema/commons/test_patterns.py
five and six digits are now allowed inside a DOI, added tests
=> fix: regex for doi
