SSRQ-SDS-FDS/ssrq-schema

- .github/workflows/pr_to_dev.yml
Just a small tweak on the CI-workflow for PRs / pushes on `dev`. PRs should now no longer trigger a deployment of the docs-page.
> [ci]: only publish docs after push on dev

- tests/utils/docs/extensions/test_md_xi.py
- utils/docs/doc_hooks.py
- utils/docs/extensions/md_xi.py
- [feat]: parser to find xi directives in text
- [feat]: handler function to resolve xincludes from text input
- [feat]: mkdocs hooks-plugin to resolve XInclude like statements
This will enable us to use statements like `-xi-include foo.xml#bar` to embedd xml snippets into the (static) markdown-files.
> A .md plugin/hook to resolve XInclude like statements

- src/schema/commons/classes.odd.xml
- src/schema/elements/author.xml
- src/schema/elements/gap.xml
- src/schema/elements/origDate.xml
- src/schema/examples/examples.xml
- src/schema/examples/gap.xml
- tests/src/schema/elements/test_author.py
- [fix]: german value for 'rm'
- [fix]: content model for tei:author
- [fix]: missing link to dating guidelines
- [docs]: more examples for tei:gap
> schema corrections and additions

- src/schema/commons/constraints.odd.xml
- src/schema/elements/handNote.xml
- tests/src/schema/elements/test_handNote.py
- tests/src/schema/test_constraints.py
- [feat]: tweaked whitespace constraint
- [feat]: constraint to ensure reference to a tei:handNote
> enhance constraints

- src/schema/commons/constraints.odd.xml
- src/schema/elements/idno.xml
- tests/src/schema/elements/test_idno.py
- tests/src/schema/test_constraints.py
This commit replaces a wrong regex with tei:textNode and adds tei:idno to the list of non-empty-elements.
> feat: changed content model of tei:idno

- src/schema/commons/classes.odd.xml
- src/schema/commons/patterns.odd.xml
- src/schema/elements/app.xml
- src/schema/elements/bibl.xml
- src/schema/elements/lem.xml
- src/schema/elements/note.xml
- src/schema/elements/rdg.xml
- src/schema/elements/supplied.xml
- src/schema/elements/witness.xml
- src/schema/examples/app.xml
- src/schema/examples/examples.xml
- tests/src/schema/elements/test_app.py
- tests/src/schema/elements/test_damage.py
- tests/src/schema/elements/test_rdg.py
- tests/src/schema/elements/test_supplied.py
- feat: changed datatypes of witness-ids + wit-attr
- docs: adopted examples and docs for new wit-datatype
- feat: extend ssrq.witness.pointer
- feat: use ssrq.witness.pointer for source in supplied
- feat: allow note inside app for text comparison
See the commits details for more infos.
> Fix the usage of app and the corresponding wit and source attributes

- src/schema/elements/quote.xml
- tests/src/schema/elements/test_quote.py
This also allows tei:seg, but not a mixed model with ssrq.content.default and tei:seg.
> [feat]: extend content model for tei:quote

- src/schema/elements/p.xml
- tests/src/schema/elements/test_p.py
This commit allows the n-attribute for tei:p to make nested tei:seg-elements for numeration purposes unnecessary.
> feat: allow attribute n for tei:p

- src/schema/elements/term.xml
- tests/src/schema/elements/test_term.py
This commit changes the model of tei:term:
- not a type attribute ist allowed with restricted values
- a lot of schematron rules have been introduced
- completely reworked tests
> feat: changed model of tei:term

- src/schema/elements/body.xml
- src/schema/examples/body.xml
- tests/src/schema/elements/test_body.py
tei:ab may now be used directly inside tei:body. So one does not have to use unnecessary tei:div-elements.
> feat: allowed tei:ab in tei:body

- src/schema/elements/seg.xml
- tests/src/schema/elements/test_seg.py
This commit allows the mixed usage of p, head and add as childs of seg.
> [feat]: extend content model for tei:seg

- src/schema/elements/subst.xml
- tests/src/schema/elements/test_subst.py
This commit makes the order of tei:del and tei:add inside tei:subst arbitrary.
> feat: changed order of tei:subst child elements

- src/schema/elements/idno.xml
- tests/src/schema/elements/test_idno.py
The constraint before would would lead to invalid idnos for editorial paratexts. The corrected regex does no correctly respect them as well as idnos without a tradition part
> [fix]: regex in regular idno-constraint

- src/schema/commons/classes.odd.xml
- src/schema/commons/datatypes.odd.xml
- src/schema/elements/measure.xml
This commit changes the following:
- "Schuh" is now a length and an area unit.
- "Klafter" is now a length, an area and a capacity unit.
- "Klafter" is no longer in a separate datatype.
Pro: It is not necessary to separatly process "Klafter" and "Schuh" in Schematron rules.
Con: These units are now duplicated in different tei:dataSpec-elements
> feat/refac: units for tei:measure

- src/schema/elements/subst.xml
- src/schema/examples/examples.xml
- src/schema/examples/subst.xml
- tests/src/schema/elements/test_subst.py
This commit allows an optional tei:lb in tei:subst. Adjusted examples and added test case.
> feat: allow lb in subst

- src/schema/commons/classes.odd.xml
- tests/src/schema/elements/test_rdg.py
It is now allowed that an ID referenced in @wit points to the @xml:id of a bibl element.
> feat: changed constraint for @wit

- utils/commons/logger.py
The changes introduced in the previous verison of SnakeMD changed the loglevel from 'DEBUG' to 'INFO', which created a lot of logs when building the docs. This commit turns of the SnakeMD logger by setting it's default level 'ERROR'.
See commit details
> [ci/build]: deactivate snakemd info logger

- src/schema/commons/datatypes.odd.xml
This commit allows the usage of "Vierling" as a valid unit for area measurements.
> feat: added Vierling as area unit

- src/schema/commons/datatypes.odd.xml
This commit allows the usage of @unit="Mütt" and @unit="Zeile" in combination with @type="area".
> feat: allow Mütt and Zeile as area units

- src/schema/commons/datatypes.odd.xml
This commit makes "Linie" a unit for length instead of a unit for capacity.
> fix: unit Linie

- src/schema/elements/seg.xml
- src/schema/elements/table.xml
- tests/src/schema/elements/test_seg.py
- tests/src/schema/elements/test_table.py
This commit allows the usage of tei:cb inside tei:seg and tei:table in analogy to tei:pb, which was already allowed there.
> feat: allow tei:cb in tei:seg and tei:table

- src/schema/commons/classes.odd.xml
- tests/src/schema/test_constraints.py
This commit prevents that any quantity attribute is zero except when there is an attribute type with the value of currency.
> feat: added schematron rule for @quantity

- src/schema/elements/date.xml
- tests/src/schema/elements/test_date.py
This commit allows the usage of @from-custom and @to-custom in tei:date when tei:date is inside tei:publicationStmt
> feat: allow @from-custom and @to-custom in tei:date

- src/schema/elements/msDesc.xml
- tests/src/schema/elements/test_msDesc.py
If the tei:text has an type 'collection' there should no be physDesc or adminInfo given, because there is no real document. This commit extends the previous rule and makes data-hacks obsolete.
> fix: schematron rule for tei:msDesc to allow missing physDesc/adminInfo

- src/schema/elements/note.xml
- tests/src/schema/elements/test_note.py
This constraint forbids the usage of @place when @type is not "original", because the place of a note is only reasonable if it is an original note present in the manuscript.
> feat: added constraint for tei:note

- src/schema/elements/list.xml
- src/schema/elements/title.xml
This pull request removes two unnecessary attributes @type from list and title,
which are defined in the TEI-Guidelines in both element definitions but not in
the class att.typed.
> fix: removed unnecessary attributes

- src/schema/commons/patterns.odd.xml
- src/schema/elements/idno.xml
- tests/src/schema/elements/test_idno.py
This commit is first step towards a clearer and simplified RegEx for
tei:idnos. It does not contain any specific implementation for canton or
volume names. It just removes outdated parts / makes some things more
'expressive'.
> feat: simplified regular expression for validation of tei:idno(s)

- src/schema/elements/origin.xml
- tests/src/schema/elements/test_origin.py
There should be no more than two tei:origDate's inside tei:origin. When there are two, their type attributes should have different values.
> feat: added restrictions for tei:origDate

- src/schema/elements/damage.xml
- tests/src/schema/elements/test_damage.py
This commit makes the content model of tei:damage a lot more
restrictive. Now just a few handful of combinations are allowed as the
content.
> feat: restrict content model of tei:damage

- src/schema/commons/translations.odd.xml
- src/schema/main.odd.xml
- utils/schema/compile.py
The included list of translations is used by various applications, which
rely on the schema and use the list for complex translations (so called
combined tags).
> feat: integrate global / common translations

- src/schema/commons/datatypes.odd.xml
Fuder can also be used to measure wine, in this case it must not be a various unit, but a capacity one.
> feat: Fuder as capacity unit

- src/docs/base/transcription/spelling/special.de.md
- src/schema/commons/classes.odd.xml
- src/schema/commons/constraints.odd.xml
- src/schema/commons/datatypes.odd.xml
- src/schema/elements/date.xml
- src/schema/elements/msDesc.xml
- src/schema/elements/origin.xml
- src/schema/elements/seal.xml
- src/schema/elements/subst.xml
- tests/src/schema/commons/test_constraints.py
- tests/src/schema/elements/test_date.py
- tests/src/schema/elements/test_msDesc.py
- tests/src/schema/elements/test_origin.py
- tests/src/schema/elements/test_precision.py
- tests/src/schema/elements/test_seal.py
- tests/src/schema/elements/test_subst.py
- added @ref for tei:seal (Link to a seal database)
- added @type for tei:subst (Replacement of a cypher
- added value "book" for tei:dimensions/@type
- added Ditto-Mark to documentation page
- added constraint for tei:date to ensure that @type='electronic' and 'print' are used only inside tei:publicationStmt
- made tei:head in tei:msDesc optional when its not the main (first) text witness
- constraint for @notAfter-custom and @notBefore-custom to ensure that they mark a valid timespan.
- eliminated @xml:lang for tei:origin
- allowed references to @calendar, @dur-iso and @period inside tei:precision/@match
> feat: small changes

- mkdocs.yml
This PR tries to improve the search of the docs. This is done by using a custom separator to build the index (see https://squidfunk.github.io/mkdocs-material/plugins/search/#config.separator). What nearly impossible:
- search for tags with queries like `<TEI/>`, but it's no possible to search for `tei` or `TEI`, which will display the page for the `<TEI/>`-element as a first result
- only show results in the current language (this should by done the following config-option: https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-search/, but does not seem to work?)
> docs: improve search by using custom separator

- src/schema/commons/patterns.odd.xml
- tests/src/schema/commons/test_patterns.py
- tests/src/schema/elements/test_time.py
This commit is in some parts a rollback of
`18b2ab27a3a7f91c8aa1a4e07e78581eafc59a39`. It's necessary, because the
introduced pattern has various problems / bugs.
> Fix pattern dur-iso (tei:time)

- utils/docs/doc_hooks.py
This fixes the following behaviour: In the french documentation all elements are referenced twice. The function now checks if the element is already referenced.
> fix: double links in navigation

- src/schema/elements/body.xml
- tests/src/schema/elements/test_body.py
- tests/src/schema/elements/test_msDesc.py
This commit implements a simpler content for text-collection (tei:text
with type 'collection') by restricting the usage to tei:bibl-elements.
Due the context dependent usage a combination of RNG and Schematron was
required.
> feat: simpler content model for text-collections

- src/schema/elements/subst.xml
- tests/src/schema/elements/test_subst.py
This commit adds a simple constraint, which will ensure, that tei:add is
never used before tei:del inside tei:subst.
> feat: ensure ordering of childs in tei:subst

- src/schema/elements/app.xml
- src/schema/examples/app.xml
- src/schema/examples/examples.xml
- **fix: removed outdated documentation from tei:app**
- **feat: added example for tei:app using space in the edited document**
> fix doc for tei app

- src/schema/elements/physDesc.xml
- tests/src/schema/commons/test_constraints.py
- tests/src/schema/elements/test_msDesc.py
- tests/src/schema/elements/test_physDesc.py
Constraint is not restricted to texts with type 'collection', because
the constraint for tei:msDesc ensures, that no tei:physDesc is used for
a collection.
> feat: constraint to check for tei:bindingDesc

- src/schema/elements/msContents.xml
- tests/src/schema/elements/test_msContents.py
When there are multiple summaries inside one container, they have to have different languages.
> feat: constraint for tei:summary inside tei:msContents
